config/routes.rb
Rails.application.routes.draw do

devise_for :users

root 'home#index'


resources :images
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
# get 'probar', to: 'controls#saludo'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
	has_one_attached :foto

	validates :description, presence: true
	validate :foto_validator

	belongs_to :user

	private
	  def foto_validator
	  	if !foto.attached?
	  		errors.add(:foto,"Es requerido")
	  	elsif foto.content_type.in?(%w(foto/png foto/jpeg))
	  		errors.add(:foto,'Debe ser un formato imagen')		
	  	end	  	
	  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_devise_params,if: :devise_controller?

	def configure_devise_params
		devise_parameter_sanitizer.permit(:sign_up) do |user|
			user.permit(:name,:email,:password,:password_confirmation)
	    end
	end
end

app/controllers/controls_controller.rb
class ControlsController < ApplicationController
	def saludo
		@myname="javier"
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if user_signed_in?
			#@books = Book.all.paginate(page: params[:page], per_page:12)
		   @image = Image.all.paginate(page: params[:page], per_page:6)
		                 .order(id: :desc)
		                 .where user_id: current_user.id
		end
	end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	before_action :set_image, only:[:show,:edit,:update,:destroy]
   
	def index
		 @image=Image.order(id: :desc)
                     .where(user_id: current_user.id)
	end

	def new
        @image=Image.new
	end



	def create
    	#render plain: params[:image].inspect
        @image=current_user.images.new(image_params)
    	if @image.save
    		return redirect_to images_path
    	else
    		return render :new
    	end
    end



    def show
    end

    def edit

    end

    def update
        if @image.update(image_params)
        	redirect_to @image
        else
        	render :edit
        end
    end


    def destroy
    	@image.destroy
    	redirect_to images_path
    end 

    private
    def image_params
    	params.require(:image).permit(:description,:foto)
    end

    def set_image
    	@image=Image.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/controls_helper.rb
module ControlsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/controls/saludo.html.erb
<h1>Hola desde el controlador <%= @myname %></h1>

app/views/home/index.html.erb
<% if user_signed_in?%>
<h1>Bienvenido <%= current_user.name %></h1>
<br>
<div class="row">
	<div class="col-4">
		
	</div>
	<div class="col-8">
		<div>
			<ul class="nav">
				<li>
					<p><strong><%= @image.count %></strong> publicadas</p>
				</li>
			</ul>
		</div>
	</div>
</div>
<div class="card-columns">
	<% @image.each do |image| %>
	<div class="card">
		<% if image.foto.attached? %>
		<%= image_tag image.foto, :style=>'width:250px;',class:"figure-img img-fluid rounded"%>
		<% end %>
		<div class="card-body">
			<%= link_to 'Editar',edit_image_path(image) %>
			<%= link_to 'Eliminar',image,method: :delete,data:{confirm:"seguro?"} %>
		</div>
		<!-- <img src="../../../public/img/bills.jpg" class="figure-img img-fluid rounded" alt=""> -->
	</div>
	<% end %>
</div>
<%= will_paginate @image %>
<br>

<% else%>
<h1>Rails</h1>
<% end %> 

app/views/images/_form.html.erb
<% if @image.errors.any? %>
   <div class="alert alert-danger">
   	 <h4 class="alert-heading">Oh No!!</h4>
   	 <p>Ha ocurrido un error</p>
   </div>
<% end %>


<p><%= title %></p>
<div class="form-group">
	<%= form_for @image ,html: { multipart: true } do |f| %>
	<%= f.label :description %>
	<%= f.text_field :description ,class:'form-control' %><br>
    <% if @image.errors[:description].any? %>
       <span class="badge badge-pill badge-danger">
       	  <%= @image.errors[:description].first %>
       </span>
    <% end %>


	<%= f.label :foto %>
	<%= f.file_field :foto %><br>
	<%= f.submit "Enviar",:class=>'btn btn-primary' %>
	<% end %>
</div>

app/views/images/_image.html.erb
<div class="col-6">
	<figure>
	<!-- 	<%= image_tag url_for(image.foto) %> -->
	<% if image.foto.attached? %>
	    <%= image_tag image %>
	<% end %>
		<img src="../../../public/img/bills.jpg" class="figure-img img-fluid rounded" alt="">
		<figcaption class="figure-caption">
			<%= link_to 'Editar',edit_image_path(image) %>
			<%= link_to 'Eliminar',image,method: :delete,data:{confirm:"seguro?"} %>
		</figcaption>
	</figure>
	
</div>
<br>

app/views/images/edit.html.erb
<%= render "form",title:'Editar foto' %>

app/views/images/index.html.erb
<h1>Imagenes</h1>
		<h1><%= current_user.name %></h1>
<br>
<div class="row">
	<div class="col-4">
		
	</div>
	<div class="col-8">
		<div>
			<ul class="nav">
				<li>
					<p><strong><%= @image.count %></strong> publicadas</p>
				</li>
			</ul>
		</div>
	</div>
</div>
<div class="card-columns">
	<% @image.each do |image| %>
	<div class="card">
		<% if image.foto.attached? %>
		<%= image_tag image.foto, :style=>'width:250px;',class:"figure-img img-fluid rounded"%>
		<% end %>
		<div class="card-body">
			<%= link_to 'Editar',edit_image_path(image) %>
			<%= link_to 'Eliminar',image,method: :delete,data:{confirm:"seguro?"} %>
		</div>
		<!-- <img src="../../../public/img/bills.jpg" class="figure-img img-fluid rounded" alt=""> -->
	</div>
	<% end %>
</div>

<br>

app/views/images/new.html.erb
<%= render "form",title:'Nueva foto' %>

app/views/images/show.html.erb
<%= @image.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Galeria</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
	<meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>
 <ul class="nav justify-content-end">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Salir', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to ' Iniciar ', new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to ' Registrarme', new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
	<div class="container">
		<div>
			<p class="notice"><%= notice %></p>
			<p class="alert"><%= alert %></p>
		</div>
		<%= yield %>
	</div>
</body>
</html>